name: dbt CI/CD

on:
  push:
    branches:
      - Prod  # Adjust this to your main branch name

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Install dbt CLI
        run: pip install dbt  # You can also use a specific version

      - name: Authenticate with dbt Cloud
        run: dbt cloud auth --token "${{ secrets.DBT_CLOUD_API_TOKEN }}"  # Enclosed in double quotes

      - name: Run dbt commands
        run: dbt run --profiles-dir .dbt
